# Generated by Django 3.0.14 on 2022-05-18 13:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20220503_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='tags',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Tag must be greater than 2 characters')]),
            preserve_default=False,
        ),
    ]
